### ISSUE TITLE
Vulnerability detected in hoek

### ISSUE THREAD

**Issue by FlipperPA** [meeting-guide/chat#1]
Hey, GitHub found a vulnerability - I could upgrade `package-lock.json` in a P.R., but I'm not sure how it would affect downstream features.

Dependency: hoek
Version: >= 5.0.0< 5.0.3
Upgrade to: ~> 5.0.3

**Comment by joshreisner** [comment]
Hey Tim, thanks for the assist. I'm just going to delete the repo,  it doesn't really do anything yet and I don't see myself working on it really.
